/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as MedicalDisclaimerRouteImport } from './routes/medical-disclaimer'
import { Route as PatientInformationRouteImport } from './routes/patient-information'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as WebsiteTermsRouteImport } from './routes/website-terms'
import { Route as ConditionsIndexRouteImport } from './routes/conditions.index'
import { Route as ConditionsSlugRouteImport } from './routes/conditions.$slug'
import { Route as KidneyHealthIndexRouteImport } from './routes/kidney-health.index'
import { Route as KidneyHealthSlugRouteImport } from './routes/kidney-health.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalDisclaimerRoute = MedicalDisclaimerRouteImport.update({
  id: '/medical-disclaimer',
  path: '/medical-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientInformationRoute = PatientInformationRouteImport.update({
  id: '/patient-information',
  path: '/patient-information',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteTermsRoute = WebsiteTermsRouteImport.update({
  id: '/website-terms',
  path: '/website-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsIndexRoute = ConditionsIndexRouteImport.update({
  id: '/conditions/',
  path: '/conditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/conditions/$slug',
  path: '/conditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KidneyHealthIndexRoute = KidneyHealthIndexRouteImport.update({
  id: '/kidney-health/',
  path: '/kidney-health/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidneyHealthSlugRoute = KidneyHealthSlugRouteImport.update({
  id: '/kidney-health/$slug',
  path: '/kidney-health/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/patient-information': typeof PatientInformationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/website-terms': typeof WebsiteTermsRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/kidney-health/$slug': typeof KidneyHealthSlugRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/kidney-health/': typeof KidneyHealthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/patient-information': typeof PatientInformationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/website-terms': typeof WebsiteTermsRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/kidney-health/$slug': typeof KidneyHealthSlugRoute
  '/conditions': typeof ConditionsIndexRoute
  '/kidney-health': typeof KidneyHealthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/patient-information': typeof PatientInformationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/website-terms': typeof WebsiteTermsRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/kidney-health/$slug': typeof KidneyHealthSlugRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/kidney-health/': typeof KidneyHealthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/medical-disclaimer'
    | '/patient-information'
    | '/privacy-policy'
    | '/website-terms'
    | '/conditions/$slug'
    | '/kidney-health/$slug'
    | '/conditions/'
    | '/kidney-health/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/medical-disclaimer'
    | '/patient-information'
    | '/privacy-policy'
    | '/website-terms'
    | '/conditions/$slug'
    | '/kidney-health/$slug'
    | '/conditions'
    | '/kidney-health'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/medical-disclaimer'
    | '/patient-information'
    | '/privacy-policy'
    | '/website-terms'
    | '/conditions/$slug'
    | '/kidney-health/$slug'
    | '/conditions/'
    | '/kidney-health/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  MedicalDisclaimerRoute: typeof MedicalDisclaimerRoute
  PatientInformationRoute: typeof PatientInformationRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  WebsiteTermsRoute: typeof WebsiteTermsRoute
  ConditionsSlugRoute: typeof ConditionsSlugRoute
  KidneyHealthSlugRoute: typeof KidneyHealthSlugRoute
  ConditionsIndexRoute: typeof ConditionsIndexRoute
  KidneyHealthIndexRoute: typeof KidneyHealthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-disclaimer': {
      id: '/medical-disclaimer'
      path: '/medical-disclaimer'
      fullPath: '/medical-disclaimer'
      preLoaderRoute: typeof MedicalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-information': {
      id: '/patient-information'
      path: '/patient-information'
      fullPath: '/patient-information'
      preLoaderRoute: typeof PatientInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-terms': {
      id: '/website-terms'
      path: '/website-terms'
      fullPath: '/website-terms'
      preLoaderRoute: typeof WebsiteTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/': {
      id: '/conditions/'
      path: '/conditions'
      fullPath: '/conditions/'
      preLoaderRoute: typeof ConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/conditions/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kidney-health/': {
      id: '/kidney-health/'
      path: '/kidney-health'
      fullPath: '/kidney-health/'
      preLoaderRoute: typeof KidneyHealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kidney-health/$slug': {
      id: '/kidney-health/$slug'
      path: '/kidney-health/$slug'
      fullPath: '/kidney-health/$slug'
      preLoaderRoute: typeof KidneyHealthSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  MedicalDisclaimerRoute: MedicalDisclaimerRoute,
  PatientInformationRoute: PatientInformationRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  WebsiteTermsRoute: WebsiteTermsRoute,
  ConditionsSlugRoute: ConditionsSlugRoute,
  KidneyHealthSlugRoute: KidneyHealthSlugRoute,
  ConditionsIndexRoute: ConditionsIndexRoute,
  KidneyHealthIndexRoute: KidneyHealthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
